# .air.toml
root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o main ./cmd"              # command to build your application
full_bin = "APP_ENV=dev ./main"             # full command to run your binary with environment variables
delay = 1000
exclude_dir = ["assets", "tmp", "vendor"]
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_regex = ["_test\\.go"]

[log]
time = false

[color]
main = "yellow"
watcher = "cyan"
build = "green"
runner = "magenta"
